import { create } from 'zustand'
import {
  emptyInfoProfile,
  emptyInfoReasons,
  emptyInfoScores,
  emptyLanguageResult,
  emptyReviewResult,
  emptyScriptResult
} from '../lib/ui/appConfig'

const emptyRewriteResult = {
  rewrittenText: '',
  changeNotes: [],
  appliedFocus: ''
}

const emptyRewriteComparison = {
  available: false,
  sourceView: 'analyzer',
  beforeText: '',
  afterText: '',
  beforeResult: null,
  afterResult: null
}

const emptyRewriteSelection = {
  active: false,
  rowIndex: null,
  fullText: '',
  targetText: '',
  afterText: ''
}

const emptyLocalReanalysis = {
  available: false,
  isLoading: false,
  error: '',
  beforeResult: null,
  afterResult: null,
  topChanges: [],
  activeModel: '',
  usage: null
}

export const useAppStore = create((set) => ({
  view: 'analyzer',
  setView: (view) => set({ view }),

  infoInput: '',
  infoScores: emptyInfoScores,
  infoReasons: emptyInfoReasons,
  infoSummary: '',
  infoProfile: emptyInfoProfile,
  infoUsage: null,
  infoActiveModel: '',
  infoError: '',
  isInfoAnalyzing: false,
  setInfoInput: (infoInput) => set({ infoInput }),
  setInfoScores: (infoScores) => set({ infoScores }),
  setInfoReasons: (infoReasons) => set({ infoReasons }),
  setInfoSummary: (infoSummary) => set({ infoSummary }),
  setInfoProfile: (infoProfile) => set({ infoProfile }),
  setInfoUsage: (infoUsage) => set({ infoUsage }),
  setInfoActiveModel: (infoActiveModel) => set({ infoActiveModel }),
  setInfoError: (infoError) => set({ infoError }),
  setIsInfoAnalyzing: (isInfoAnalyzing) => set({ isInfoAnalyzing }),

  reviewMode: 'preflight',
  reviewPlatform: '通用',
  reviewTitle: '',
  reviewBody: '',
  reviewCover: '',
  reviewResult: emptyReviewResult,
  reviewUsage: null,
  reviewActiveModel: '',
  reviewError: '',
  isReviewAnalyzing: false,
  setReviewMode: (reviewMode) => set({ reviewMode }),
  setReviewPlatform: (reviewPlatform) => set({ reviewPlatform }),
  setReviewTitle: (reviewTitle) => set({ reviewTitle }),
  setReviewBody: (reviewBody) => set({ reviewBody }),
  setReviewCover: (reviewCover) => set({ reviewCover }),
  setReviewResult: (reviewResult) => set({ reviewResult }),
  setReviewUsage: (reviewUsage) => set({ reviewUsage }),
  setReviewActiveModel: (reviewActiveModel) => set({ reviewActiveModel }),
  setReviewError: (reviewError) => set({ reviewError }),
  setIsReviewAnalyzing: (isReviewAnalyzing) => set({ isReviewAnalyzing }),

  scriptPlatform: '通用',
  scriptVideoLength: '短视频',
  scriptFormat: '纯文案',
  scriptTitle: '',
  scriptBody: '',
  scriptResult: emptyScriptResult,
  scriptUsage: null,
  scriptActiveModel: '',
  scriptError: '',
  isScriptAnalyzing: false,
  setScriptPlatform: (scriptPlatform) => set({ scriptPlatform }),
  setScriptVideoLength: (scriptVideoLength) => set({ scriptVideoLength }),
  setScriptFormat: (scriptFormat) => set({ scriptFormat }),
  setScriptTitle: (scriptTitle) => set({ scriptTitle }),
  setScriptBody: (scriptBody) => set({ scriptBody }),
  setScriptResult: (scriptResult) => set({ scriptResult }),
  setScriptUsage: (scriptUsage) => set({ scriptUsage }),
  setScriptActiveModel: (scriptActiveModel) => set({ scriptActiveModel }),
  setScriptError: (scriptError) => set({ scriptError }),
  setIsScriptAnalyzing: (isScriptAnalyzing) => set({ isScriptAnalyzing }),

  languageTextType: '通用',
  languageTitle: '',
  languageBody: '',
  languageResult: emptyLanguageResult,
  languageUsage: null,
  languageActiveModel: '',
  languageError: '',
  isLanguageAnalyzing: false,
  setLanguageTextType: (languageTextType) => set({ languageTextType }),
  setLanguageTitle: (languageTitle) => set({ languageTitle }),
  setLanguageBody: (languageBody) => set({ languageBody }),
  setLanguageResult: (languageResult) => set({ languageResult }),
  setLanguageUsage: (languageUsage) => set({ languageUsage }),
  setLanguageActiveModel: (languageActiveModel) => set({ languageActiveModel }),
  setLanguageError: (languageError) => set({ languageError }),
  setIsLanguageAnalyzing: (isLanguageAnalyzing) => set({ isLanguageAnalyzing }),

  isRewriteOpen: false,
  rewriteSourceView: 'analyzer',
  rewriteMode: 'conservative',
  rewriteOriginalText: '',
  rewriteSummary: '',
  rewriteProblems: [],
  rewriteSuggestions: [],
  rewriteCustomInstruction: '',
  rewriteResult: emptyRewriteResult,
  rewriteUsage: null,
  rewriteActiveModel: '',
  rewriteError: '',
  isRewriting: false,
  rewriteComparison: emptyRewriteComparison,
  rewriteComparisonTab: 'scores',
  rewriteTextView: 'side_by_side',
  rewriteSelection: emptyRewriteSelection,
  rewriteLocalReanalysis: emptyLocalReanalysis,
  setIsRewriteOpen: (isRewriteOpen) => set({ isRewriteOpen }),
  setRewriteSourceView: (rewriteSourceView) => set({ rewriteSourceView }),
  setRewriteMode: (rewriteMode) => set({ rewriteMode }),
  setRewriteOriginalText: (rewriteOriginalText) => set({ rewriteOriginalText }),
  setRewriteSummary: (rewriteSummary) => set({ rewriteSummary }),
  setRewriteProblems: (rewriteProblems) => set({ rewriteProblems }),
  setRewriteSuggestions: (rewriteSuggestions) => set({ rewriteSuggestions }),
  setRewriteCustomInstruction: (rewriteCustomInstruction) => set({ rewriteCustomInstruction }),
  setRewriteResult: (rewriteResult) => set({ rewriteResult }),
  setRewriteUsage: (rewriteUsage) => set({ rewriteUsage }),
  setRewriteActiveModel: (rewriteActiveModel) => set({ rewriteActiveModel }),
  setRewriteError: (rewriteError) => set({ rewriteError }),
  setIsRewriting: (isRewriting) => set({ isRewriting }),
  setRewriteComparison: (rewriteComparison) => set({ rewriteComparison }),
  setRewriteComparisonTab: (rewriteComparisonTab) => set({ rewriteComparisonTab }),
  setRewriteTextView: (rewriteTextView) => set({ rewriteTextView }),
  setRewriteSelection: (rewriteSelection) => set({ rewriteSelection }),
  setRewriteLocalReanalysis: (rewriteLocalReanalysis) => set({ rewriteLocalReanalysis }),
  resetRewriteState: () =>
    set({
      rewriteMode: 'conservative',
      rewriteOriginalText: '',
      rewriteSummary: '',
      rewriteProblems: [],
      rewriteSuggestions: [],
      rewriteCustomInstruction: '',
      rewriteResult: emptyRewriteResult,
      rewriteUsage: null,
      rewriteActiveModel: '',
      rewriteError: '',
      isRewriting: false,
      rewriteComparison: emptyRewriteComparison,
      rewriteComparisonTab: 'scores',
      rewriteTextView: 'side_by_side',
      rewriteSelection: emptyRewriteSelection,
      rewriteLocalReanalysis: emptyLocalReanalysis
    })
}))
