export const infoAnalysisSchemaPrompt = [
  '{',
  '  "scores": {',
  '    "confidence": 0,',
  '    "verifiability": 0,',
  '    "signal": 0,',
  '    "clarity": 0,',
  '    "insight": 0,',
  '    "taste": 0,',
  '    "manipulation": 0',
  '  },',
  '  "reasons": {',
  '    "confidence": "string",',
  '    "verifiability": "string",',
  '    "signal": "string",',
  '    "clarity": "string",',
  '    "insight": "string",',
  '    "taste": "string",',
  '    "manipulation": "string"',
  '  },',
  '  "summary": "string",',
  '  "profile": {',
  '    "thought_system_label": "string",',
  '    "thought_system_reason": "string",',
  '    "core_judgment": "string",',
  '    "slop_risk": "string",',
  '    "argument_shape": "string",',
  '    "attention_worth": "string",',
  '    "weakest_link": "string"',
  '  }',
  '}'
]

export const infoAnalysisConstraintPrompt = [
  '- 所有分数必须使用 0 到 100 的整数，不要使用 0 到 10 或 1 到 10 量表。',
  '- 默认偏严格，不要轻易给高分。',
  '- 对 AI slop、伪洞察、低信息密度内容，signal、insight 和 taste 应明显偏低。',
  '- 对无证据却语气笃定的内容，confidence 应明显偏低。',
  '- 对没有可核查依据的内容，verifiability 应明显偏低。',
  '- 对靠话术驱动而非论证驱动的内容，manipulation 应偏高。',
  '- 如果表达流畅但实质空洞，不能因为像样就给高分。',
  '- 只有在内容兼具证据、准确判断、真实信息量和清晰表达时，才允许高分。',
  '- reasons 每项控制在 30 个中文字符以内。',
  '- summary 控制在 80 个中文字符以内。',
  '- profile 中每一项控制在 50 个中文字符以内。',
  '- thought_system_label 必须从以下标签中选择最贴切的一个：经验主义、叙事驱动、观点先行、证据驱动、情绪操控、姿态表达、伪深刻、信息压缩型、洞察型、营销话术型。'
]
