export const languageAnalysisSchemaPrompt = [
  '{',
  '  "summary": "string",',
  '  "scores": {',
  '    "syntax_control": 0,',
  '    "long_sentence_control": 0,',
  '    "rhetoric_effectiveness": 0,',
  '    "rhythm_structure": 0,',
  '    "tone_stability": 0,',
  '    "expressive_tension": 0,',
  '    "style_distinctness": 0,',
  '    "posture_density": 0',
  '  },',
  '  "reasons": {',
  '    "syntax_control": "string",',
  '    "long_sentence_control": "string",',
  '    "rhetoric_effectiveness": "string",',
  '    "rhythm_structure": "string",',
  '    "tone_stability": "string",',
  '    "expressive_tension": "string",',
  '    "style_distinctness": "string",',
  '    "posture_density": "string"',
  '  },',
  '  "detected_features": {',
  '    "rhetorical_devices": ["string"],',
  '    "sentence_patterns": ["string"],',
  '    "style_modes": ["string"]',
  '  },',
  '  "auxiliary": {',
  '    "keywords": ["string"],',
  '    "repetition_note": "string",',
  '    "transition_note": "string",',
  '    "homogenization_note": "string"',
  '  },',
  '  "problems": ["string"],',
  '  "revision_suggestions": {',
  '    "sentence": "string",',
  '    "rhythm": "string",',
  '    "rhetoric": "string",',
  '    "tone": "string"',
  '  },',
  '  "commentary": {',
  '    "style_summary": "string",',
  '    "language_mechanism": "string",',
  '    "dominant_effect": "string",',
  '    "risk_note": "string"',
  '  },',
  '  "profile": {',
  '    "core_strength": "string",',
  '    "core_weakness": "string",',
  '    "writer_tendency": "string",',
  '    "reading_experience": "string"',
  '  }',
  '}'
]

export const languageAnalysisConstraintPrompt = [
  '- 所有分数必须使用 0 到 100 的整数，不要使用 0 到 10 或 1 到 10 量表。',
  '- reasons 每项控制在 30 个中文字符以内。',
  '- summary 控制在 80 个中文字符以内。',
  '- detected_features 每类最多返回 5 项，优先保留最有解释力的标签。',
  '- auxiliary.keywords 返回 3 到 6 个核心关键词；其余 auxiliary 字段控制在 36 个中文字符以内。',
  '- problems 最多返回 5 项，每项控制在 28 个中文字符以内。',
  '- revision_suggestions 每项控制在 60 个中文字符以内。',
  '- commentary 每项控制在 50 个中文字符以内。',
  '- profile 每项控制在 40 个中文字符以内。'
]
