export const reviewAnalysisSchemaPrompt = [
  '{',
  '  "risk_level": "低 / 中 / 高",',
  '  "publish_recommendation": "string",',
  '  "scores": {',
  '    "violation_risk": 0,',
  '    "marketing_risk": 0,',
  '    "medical_risk": 0,',
  '    "financial_risk": 0,',
  '    "vulgarity_risk": 0,',
  '    "traffic_redirect_risk": 0,',
  '    "headline_misleading_risk": 0',
  '  },',
  '  "reasons": {',
  '    "violation_risk": "string",',
  '    "marketing_risk": "string",',
  '    "medical_risk": "string",',
  '    "financial_risk": "string",',
  '    "vulgarity_risk": "string",',
  '    "traffic_redirect_risk": "string",',
  '    "headline_misleading_risk": "string"',
  '  },',
  '  "hit_points": [',
  '    {',
  '      "text": "string",',
  '      "reason": "string",',
  '      "severity": "低 / 中 / 高",',
  '      "platform_note": "string"',
  '    }',
  '  ],',
  '  "fix_suggestions": ["string"],',
  '  "appeal_potential": "低 / 中 / 高",',
  '  "appeal_reason": "string",',
  '  "review_profile": {',
  '    "core_issue": "string",',
  '    "risk_style": "string",',
  '    "platform_sensitivity": "string",',
  '    "suggested_action": "string"',
  '  }',
  '}'
]

export const reviewAnalysisConstraintPrompt = [
  '- 所有分数必须使用 0 到 100 的整数，不要使用 0 到 10 或 1 到 10 量表。',
  '- reasons 每项控制在 30 个中文字符以内。',
  '- publish_recommendation 控制在 40 个中文字符以内。',
  '- hit_points 最多返回 5 项，优先列最危险的。',
  '- fix_suggestions 最多返回 4 项，每项控制在 30 个中文字符以内。',
  '- review_profile 每项控制在 40 个中文字符以内。'
]
