export const scriptEvaluationSchemaPrompt = [
  '{',
  '  "summary": "string",',
  '  "totals": {',
  '    "hook_power": 0,',
  '    "narrative_power": 0',
  '  },',
  '  "scores": {',
  '    "hook_strength": 0,',
  '    "retention_potential": 0,',
  '    "rhythm_control": 0,',
  '    "memorability": 0,',
  '    "setup_clarity": 0,',
  '    "conflict_strength": 0,',
  '    "structure_integrity": 0,',
  '    "emotion_build": 0',
  '  },',
  '  "reasons": {',
  '    "hook_strength": "string",',
  '    "retention_potential": "string",',
  '    "rhythm_control": "string",',
  '    "memorability": "string",',
  '    "setup_clarity": "string",',
  '    "conflict_strength": "string",',
  '    "structure_integrity": "string",',
  '    "emotion_build": "string"',
  '  },',
  '  "strengths": ["string"],',
  '  "problems": ["string"],',
  '  "revision_suggestions": {',
  '    "opening": "string",',
  '    "middle": "string",',
  '    "ending": "string",',
  '    "format": "string"',
  '  },',
  '  "fit": {',
  '    "best_format": "string",',
  '    "short_video_fit": "string",',
  '    "long_video_fit": "string",',
  '    "platform_note": "string"',
  '  },',
  '  "profile": {',
  '    "core_selling_point": "string",',
  '    "biggest_weakness": "string",',
  '    "audience_pull": "string",',
  '    "story_shape": "string"',
  '  }',
  '}'
]

export const scriptEvaluationConstraintPrompt = [
  '- 所有分数必须使用 0 到 100 的整数，不要使用 0 到 10 或 1 到 10 量表。',
  '- strengths 最多返回 4 项，每项控制在 24 个中文字符以内。',
  '- problems 最多返回 5 项，每项控制在 28 个中文字符以内。',
  '- summary 控制在 80 个中文字符以内。',
  '- reasons 每项控制在 30 个中文字符以内。',
  '- revision_suggestions 每项控制在 60 个中文字符以内。',
  '- fit 中每项控制在 40 个中文字符以内。',
  '- profile 每项控制在 40 个中文字符以内。'
]
